# Generated by Django 2.1.5 on 2019-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=100)),
                ('definition', models.TextField(blank=True, null=True)),
                ('related_words', models.ManyToManyField(related_name='_word_related_words_+', to='backend.Word')),
            ],
        ),
    ]
